apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-8504c062-4096-49e2-9d4a-2d204e13cbdf
  name: devfile-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-75-tenant/load-app-8504c062-4096-49e2-9d4a-2d204e13cbdf/devfile-sample@sha256:12c611495302b38981bdf031e59e9d8742e9e3d23287d2afda1dfe63b6739135
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
